### ISSUE TITLE
Unable to install the dependency

### ISSUE THREAD

**Issue by PaoloRollo** [0xPolygonID/polygonid-flutter-sdk#340]
Following the guide available [here](https://devs.polygonid.com/docs/wallet/wallet-sdk/polygonid-sdk/polygonid-sdk-plugin/), I tried both:

```yaml
polygonid_flutter_sdk: ^2.2.8
```

and

```yaml
  polygonid_flutter_sdk:
    git:
      url: https://github.com/0xPolygonID/polygonid-flutter-sdk.git
      ref: main
```

In the `pubspec.yaml` file, but with no success. In the first case, the error I get is :

`Because project depends on polygonid_flutter_sdk any which doesn't exist (could not find package polygonid_flutter_sdk at https://pub.dev), version solving failed.`. In fact if you search for this SDK on pub.dev you get 404 (you can double check [here](https://pub.dev/packages/polygonid_flutter_sdk)).

Using github instead, the download of the package remains stuck and I'm unable to install the sdk.

How can I use this sdk in my Flutter project?
